# -*- coding: utf-8 -*-
"""Atividade 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhDj7rD2nDNLbuyanx5Ib85U3g2VhuKo
"""

import requests
import pandas as pd

from IPython.display import display

api_key = "a593ebbb7d133485e2ae48b0f79c73c1"

url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&language=pt-BR"

response = requests.get(url)
data = response.json()

filmes = []

for movie in data['results']:
    df = {'Titulo': movie['title'],
          'Data de lançamento': movie['release_date'],
          'Visão geral': movie['overview'],
          'Votos': movie['vote_count'],
          'Média de votos': movie['vote_average']}

    filmes.append(df)

df = pd.DataFrame(filmes)
display(df)