# Usando a imagem base do Python
FROM python:3.8

# Copiando o script Python para a imagem
COPY carguru.py /app/carguru.py

# Definindo o diretório de trabalho
WORKDIR /app

EXPOSE 3000

# Executando o script Python quando o container for iniciado
CMD ["python", "carguru.py"]
 