# -*- coding: utf-8 -*-
"""ex2pt1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1te8XRJdCiH0AY2swE7O5f7rIK6rOV4Ya
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
!tar xf spark-3.1.2-bin-hadoop2.7.tgz
!pip install -q findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.2-bin-hadoop2.7"

import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()
!wget https://raw.githubusercontent.com/brendacmsousa/Programa_de_Bolsas_Compass-Uol/master/README.md
df = spark.read.text("README.md")
from pyspark.sql.functions import explode, split, desc

words = df.select(explode(split(df.value, " ")).alias("word"))
word_counts = words.groupBy("word").count().orderBy(desc("count"))

word_counts.show()