# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imOP2WzdG_5jfOgqB2ZWyHJENEQwPeCU
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import when, rand, expr
from pyspark.sql.types import StringType
from pyspark.sql import functions as F

spark = SparkSession.builder.master("local[*]").appName("Exercicio Intro").getOrCreate()

# 1. Leitura do arquivo e exibição das primeiras linhas:
df_nomes = spark.read.csv("nomes_aleatorios.txt", header=False, inferSchema=True)
df_nomes.show(5)

# 2. Renomear a coluna, imprimir o esquema e mostrar 10 linhas:
df_nomes = df_nomes.withColumnRenamed("_c0", "Nomes")
df_nomes.printSchema()
df_nomes.show(10)

#3.Adicionar a coluna Escolaridade:
df_nomes = df_nomes.withColumn("Escolaridade",
                               when(df_nomes.Nomes.isNotNull(), "Fundamental")
                              .when(df_nomes.Nomes.isNotNull(), "Medio")
                              .when(df_nomes.Nomes.isNotNull(), "Superior"))

# 4. Adicionar a coluna Pais:
df_nomes = df_nomes.withColumn("Pais", F.expr(f"array('Brasil', 'Argentina', 'Chile', 'Colombia', 'Equador', 'Peru', 'Uruguai', 'Paraguai', 'Bolivia', 'Venezuela', 'Suriname', 'Guiana', 'Uruguai')[int(rand() * size(array('Brasil', 'Argentina', 'Chile', 'Colombia', 'Equador', 'Peru', 'Uruguai', 'Paraguai', 'Bolivia', 'Venezuela', 'Suriname', 'Guiana', 'Uruguai')))]"))

#5. Adicionar a coluna AnoNascimento:
df_nomes = df_nomes.withColumn("AnoNascimento", expr(f"floor(rand() * (2010 - 1945 + 1) + 1945)"))

#6. Selecionar pessoas que nasceram neste século:
df_select = df_nomes.filter(df_nomes.AnoNascimento >= 2000)
df_select.show(10)

#7. Selecionar pessoas que nasceram neste século usando Spark SQL:
df_nomes.createOrReplaceTempView("pessoas")
df_select_sql = spark.sql("SELECT * FROM pessoas WHERE AnoNascimento >= 2000")
df_select_sql.show(10)

#8. Contar o número de pessoas da geração Millennials usando método select:
count_millennials = df_nomes.filter((df_nomes.AnoNascimento >= 1980) & (df_nomes.AnoNascimento <= 1994)).count()
print(f"Número de Millennials: {count_millennials}")

#9. Contar o número de pessoas da geração Millennials usando Spark SQL:
count_millennials_sql = spark.sql("SELECT COUNT(*) FROM pessoas WHERE AnoNascimento BETWEEN 1980 AND 1994").collect()[0][0]
print(f"Número de Millennials (Spark SQL): {count_millennials_sql}")

#10. Quantidade de pessoas por país e geração usando Spark SQL:
df_nomes.createOrReplaceTempView("pessoas")

df_geracoes = spark.sql("""
SELECT Pais,
       CASE WHEN AnoNascimento BETWEEN 1944 AND 1964 THEN 'Baby Boomers'
            WHEN AnoNascimento BETWEEN 1965 AND 1979 THEN 'Geração X'
            WHEN AnoNascimento BETWEEN 1980 AND 1994 THEN 'Millennials'
            WHEN AnoNascimento BETWEEN 1995 AND 2015 THEN 'Geração Z'
       END AS Geracao,
       COUNT(*) AS Quantidade
FROM pessoas
GROUP BY Pais, Geracao
ORDER BY Pais, Geracao
""")

df_geracoes.show()