# -*- coding: utf-8 -*-
"""Tarefa 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18lIKH9YmHKr-LKfIPYtto0WCiYKpKLOP
"""

import os
import pandas as pd
import boto3
from datetime import datetime

# Configuração de credenciais usando variáveis de ambiente
os.environ['AWS_ACCESS_KEY_ID'] = 'ASIAU6YMVBVMXXFTSHKP'
os.environ['AWS_SECRET_ACCESS_KEY'] = '3RHCZt/X6YbsPDgJdz0Vd/2oGMoWUE98G1NE1tGB'
os.environ['AWS_SESSION_TOKEN'] = 'IQoJb3JpZ2luX2VjEIn//////////wEaCXVzLWVhc3QtMSJHMEUCIBU9+qh+9pceJRp+e1lOaVtVfTXlmbdLdExdSe3FcBPqAiEAvTgiCHmSsG1ThsrK8VQW6lysKasjr9YGb90ceOUr9boqpgMI8v//////////ARAAGgwzNDA5Mzk1NzQ2MTciDPFZ0tnjXd6h7zx8Nyr6Asz0mkIxgkjGsF2gSpaBnTnZfPFs1XFuDwX2nLDMJ9rKSRCJ1l4qIry0jAAxCRObc2oqGrwPa4chT174RNes5MDPajkbG3ex38Fyw8BkGXwOKtH+baT7K5YMgc9S8TqxF84Bl/qR2/B8e2vDDj2LCq1S/6Pty4H52xF6gbn6pja8n+yP5HZ1neuJP/5LnzJoCtRdrRldND32cpZDKA0Pb3C9bMf4ddL5Pfm1DrZCLXfiJkIRdXSRU+M4aqI0xsdjpQwxzufzWDG4cEO8dR9ef7O/RHRfexxNLHwW4rOJvfUCfxO0TGHzGE+3QIBZVsjcvvYcqavXrq1F5Y9bRgNnu6t+Ze5arcsQuQfZmFhwjYOhzrKOnndLSwP0/jvC5ctervPbDGNYPSJLeNpPl/zPVxQ/fUTu9mCkLO79lBSDSIp44QjTQjIzeghZI2by4gzly0BdBtqA+1qRI3EdKBoTH+k2VrH4XiwEvkMhOrL2n7LI3rzcxNQsNSR33DDq2NerBjqmAc2lrkpm1DMiYXRnV0pnVzp+rnLH6dfxxzhe0H6aOSPW6jj1v0jGb7SW/kZRDZnkNa8NTfQkE01LPFfZDgfIQF0fLuwBFhFU+0DifXHzagtjIHX4YHUtmVx3KZzV8+8WGaVS2H68J/v4NP9k3/9K9SEnUaLPrWPLerACczsPO1tz8ZfnKzSbNM5ceJY27+9dA3jgInUIX1JfQR999W5c9zoOTQu/978='

def upload_to_s3(mybucketex01, storage_layer, data_source, data_format, data_spec, file_name, data):
    session = boto3.Session(
      aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
      aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
      aws_session_token=os.environ["AWS_SESSION_TOKEN"],
  )
    s3 = session.resource('s3')
    now = datetime.now()
    date_folder = now.strftime("%Y/%m/%d")
    s3_path = f"{mybucketex01}/Raw/{storage_layer}/{data_source}/{data_format}/{date_folder}/{file_name}"
    print(s3_path)
    s3.Bucket(mybucketex01).put_object(Key=s3_path, Body=data)

def read_csv_and_upload(file_path, mybucketex01, storage_layer, data_source, data_format, data_spec):
    df = pd.read_csv(file_path, delimiter='|')
    file_name = file_path.split('/')[-1]
    upload_to_s3(mybucketex01, storage_layer, data_source, data_format, data_spec, file_name, df.to_csv(index=False))

# Leitura e envio do arquivo de filmes
read_csv_and_upload('/content/movies.csv', 'mybucketex01', 'Local', 'CSV', 'Movies', '2022/05/02/movies.csv')

# Leitura e envio do arquivo de séries
read_csv_and_upload('/content/series.csv', 'mybucketex01', 'Local', 'CSV', 'Series', '2022/05/02/series.csv')

!pip install boto3