# -*- coding: utf-8 -*-
"""Tarefa 3.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDIPPurKj6m9mtXNyI-Hrg7DG01Tt-T2
"""

animais = ['Leão', 'Elefante', 'Girafa', 'Tigre', 'Zebra', 'Urso', 'Gorila', 'Cobra', 'Leopardo', 'Rinoceronte', 'Hipopótamo', 'Jaguar', 'Crocodilo',
           'Lobo', 'Panda', 'Orangotango', 'Hiena', 'Suricata', 'Camelo', 'Canguru']

# Ordena a lista de animais em ordem alfabética
animais_ordenados = sorted(animais)

# Imprime os animais ordenados
for animal in animais_ordenados:
    print(animal)

# Salva os animais em um arquivo CSV
with open('animais.csv', 'w') as file:
    for animal in animais_ordenados:
        file.write(animal + '\n')